---
title: "Response to Reviewers"
date: "2022-09-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Major comments from Reviewer 1

Comments to the Author(s)
Please see attached file for comments.

## Major comments from Reviewer 2

> While Sections 2 and 3 are well done and complete, Sections 4 and 5 are weak and seem incomplete and unpolished.  

>Likewise the Opportunities section should be expanded to include the proliferation of Sports Analytics conferences.  

> My largest concern is that a cursory discussion of player contribution or player ratings is given and this seems a major oversight of one of the "big ideas" in sports analytics given the focus on this topic in many sports.  See, for example, Mark Glickman's recent presentation on this at the 2022 Joint Statistical Meetings.  I don't think that Hvattum (2019) is sufficient to cover the area of player contribution.

## Minor comments from Reviewer 1

> In the second sentence, baseball is introduced as a "naturally discrete" sport, but there are certainly many things about baseball which are not discrete, as talked about later in the article. It would be helpful to clarify what is meant by discrete in this setting.

We have added a paragraph clarify the distinction between "discrete" and "continuous" sports. In order to maintain the flow of the narrative, the paragraph does not appear here, but rather at the beginning of Section 2. 

> Also, later on in the first paragraph, it would be useful to have a citation or two about the changes being brought about in baseball due to analytics.

We believe that the last sentence of the first paragraph does exactly that. 

> In Section 2.1, Figure 1 (George Lindsey's calculations) is introduced before the reader even knows who George Lindsey is. 

We think this is mainly due to LaTeX floating the figure suboptimally, and this can be corrected in the page proofs. We have moved the sentence introducing Figure 1 and Table 1 until after the mention of Lindsey's work in the text to mitigate this problem. 

> Furthermore, the expected run matrix is displayed "in its more familiar form", but I would venture for most readers of this article, no form would be familiar.

We have replaced "more familiar" with "most common". 

> I think the caption does explain the matrix nicely, although it might be useful to point out from which column in Lindsey's table the matrix is derived.

Indeed, we note which column corresponds to the expected run matrix in the caption. 

> In Figure 2, I found it quite surprising that the expected point value was so negative at the 95 yard line. Were safeties very common in this era of American football? This might be worth mentioning/discussing.

We have added a sentence to address this. The expected value was unrealistic because the model is linear, which is a flaw of this approach.

> The title of Section 2.3 seems to indicate that the aforementioned sports have only discrete states, but this is not always the case. Some clarification would be useful here. In general, the organization of Section 2 is confusing. It first seems to be going sport by sport, but then 2.3 is about several different sports and then 2.4 is on a general topic altogether. As is, it reads somewhat disjointed and is hard to follow. Section 3 flows much better in this sense.

We thank the reviewer for this observation. We have reorganized the subsections of Section 2 with more explicit titles to improve the flow and readability of this Section. 

> Table 2 seems unnecessary, as the content is entirely summarized in the text.

We have removed Table 2. 

> After the comprehensive views in Sections 2 and 3, Section 4 seems sparse on details. Much detail is given on the Bradley-Terry model, but only one example is given of a possible usage. Has this been used in other sports? Has it changed how we think about those sports or team strategies? An explanation of Elo rating should be given; I for one have no knowledge of how to compute it.

We thank the reviewer for this excellent suggestion. We have added a subsection on Elo ratings, with a mathematical definition followed by a calculation example. This example uses the `chessR` package, which ties into and strengthens our discussion of tools in the next chapter. 

> There is a large body of literature on Bayesian state-space models in sports outside of the Glickman and Stern paper, mainly in soccer/association football. See for example Koopman and Lit (2015) and the various references in its introduction.

Thank you for this suggestion. We have added a reference to Koopman's paper. 


> As mentioned earlier, Section 5 seems sparse on details, and furthermore it seems odd to choose chess as the case study when it has barely been mentioned previously in the article. 

Our new subsection on Elo ratings also discusses chess, so now, the reader has already seen a methodological application to chess by the time they get to the case study. We have also added a new subsection to this Section about baseball, in the hopes of fleshing it out. 

> I think this section could use a table of some sort, perhaps something that summarizes the CRAN task view at a high level. Another potential would be a figure which shows a typical workflow of sports analytics as explained in the text.

We have added a table summarizing the sport-specific packages that are available on CRAN.

> Figure 6 doesn't add much to the text; I don't think the reader better understands sports analytics by visualizing many team colors. Instead, it would be better to show  how the theming can lead to a more impactful graphic for sports, i.e. show how that package might be used in a real-world setting.

XX

> For Section 6, there is also now a "Big Data Derby" in horse racing.

We thank the reviewer for this suggestion. We have added a reference to it. 

> All in all, I think the article explains the ideas well and covers a lot of ground, but more care should be taken towards the organization and what to include as figures. The last half of the paper has a very different pace than the first half. I think a common theme in the paper is the rise in tracking data and how that has impacted sports–perhaps that idea could be better unified and stated in a specific section of the article, or at the very least noted in the conclusion.

XX

> Page 4, line 56: Needs to be some sort of separation between the "absorbing states" and "touchdown"

We have added "absorbing states that include touchdowns..."

> Page 5, line 56: Typo for "causal"

Fixed. 

> Page 5, line 57: Should be "too conservative"

Fixed. 

> Page 7, line 37: Should be "led" not "lead"

Fixed. 

## Minor comments from Reviewer 2

> Pages 3,4, 5: The use of historical tables and data is powerful.  However, I worry about the quality of the images particularly Figure 2.

We share this concern. We are also uncertain about any licensing restrictions. We have left the images as is for now, and will wait direction from Wiley. 

> Page 6, line 8:  "the effect may be overstated" is somewhat ambiguous.  Is it the

XX Quang or Greg to respond

> Page 6, line 53: Is the "!" warranted here for conditioning on a 9-dimensional vector?

We have replaced the exclamation point with a period. 

> Page 8, line 53: There is also work on expected possession in ice hockey, see Stokes et al. https://hockey-graphs.com/2021/07/06/bayesian-space-time-models-for-expected-possession-added-value-part-1-of-2/

We have added a reference to this work, but are also cognizant that Wiley policy may not permit a citation to this unpublished work:

>> "preprint articles should not be cited in WIREs manuscripts as review articles should discuss and draw conclusions only from peer-reviewed research. Remember that original research/unpublished work should also not be included as it has not yet been peer-reviewed and could put the work in jeopardy of getting published in the primary press."

> 9, 17: Is Player Win Average relevant to win probability?  This is more of a player contribution metric than a win probability metric.  I would rather see a brief exposition of Tango et al (2007) here. 

Given that Albert (2015) previously published an article on this topic in this same journal series, we did not include a treatment of player contribution metrics in our paper. Our opinion is that this is redundant given Albert's article. 

> 9, 47: Gridiron football is a lovely term but for this audience, I think it needs to be clarified.

We like the term too, but have changed this to "American football."

> 10, 52: "In this paper", the "this" seems ambiguous.

We have replaced this with "Deshpande & Jensen"

> 11, 36: Table 3, why order this table alphabetically, why not by ability level?

We have ordered the rows of Table 3 by descending order of ability. 

> 11, 50: Given how much fivethirtyeight.com uses Elo ratings for all kinds of sports, it is probably worth mentioning their work as examples.

We have added the sentence: "Elo ratings are used extensively for rankings of teams in numerous sports by the data journalists at FiveThirtyEight.com." 

> 12, 1: As noted above, Section 4 feels much weaker than Sections 2 and 3 which are strong.  Perhaps a look at Pythagorean methods as a historical introduction to this topic.

We thank the reviewer for this excellent idea. We have added a new subsection on Expected Winning Percentages models to the beginning of Section 4. 

> 12, 23: This is not much of a case study.  Perhaps some additional information on the data available, ways it could be used to calculate game state expected valued, win probability, player ratings….

We have connected the case study in chess to the new subsection on Elo ratings and the subsequent subsection on graphical tools. We hope that these explicit connections to additional content will make this subsection feel more substantial. 
In addition, we have added new subsection to this Section with a different case study in baseball about the evolution of data, tools, and statistical methodologies. We hope that this additional content will help to flesh out the value of these tools. 


> 12, 37: Theming *teamcolors* is a great *R* package, not sure it is part of the "big ideas" in sports analytics.  A single line in the first paragraph of this section would seem to be better.

We have added examples from the `SportyR` package, which draws playing surfaces, to help flesh out this subsection. We also replaced the previous Figure 6 with a new Figure 5 that illustrates how the use of team colors is particularly impactful for sports-releated data graphics.  

> 13, 35: Add a citation for Big Data Cup, https://www.stathletes.com/big-data-cup/, for SABR Diamond Dollars Case Competition, https://sabr.org/analytics/case, Big Data Derby https://www.kaggle.com/competitions/big-data-derby-2022, and maybe more. 

Thank you for these suggestions. We have added them. 

> 13, 43-53: don't think there is a need for a bulleted list here.

We have removed the bulleted lists. 